name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET latest LTS
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: latest
          dotnet-channel: LTS

      - name: Build
        run: dotnet build src/RunX/RunX.csproj --configuration Release

      - name: Publish AOT
        run: dotnet publish src/RunX/RunX.csproj --configuration Release --output publish

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: runx
          path: publish/runx.*
